//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeusPark.Data.MySql
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public long CommentID { get; set; }
        public int ProductID { get; set; }
        public string Content { get; set; }
        public string Reply { get; set; }
        public System.DateTime SubmitTime { get; set; }
        public string SubmitBy { get; set; }
        public Nullable<int> Star { get; set; }
    }
}
