//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeusPark.Data.MySql
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class zeusparkEntities : DbContext
    {
        public zeusparkEntities()
            : base("name=zeusparkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<category> categories { get; set; }
        public DbSet<deliveryinfo> deliveryinfoes { get; set; }
        public DbSet<groupvalue> groupvalues { get; set; }
        public DbSet<location> locations { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<productcategory> productcategories { get; set; }
        public DbSet<productextentionattribute> productextentionattributes { get; set; }
        public DbSet<productgroup> productgroups { get; set; }
        public DbSet<productimage> productimages { get; set; }
        public DbSet<productproperty> productproperties { get; set; }
        public DbSet<productsaleinfo> productsaleinfoes { get; set; }
        public DbSet<productstatu> productstatus { get; set; }
        public DbSet<skuinfo> skuinfoes { get; set; }
        public DbSet<useraccount> useraccounts { get; set; }
        public DbSet<uploadhistory> uploadhistories { get; set; }
        public DbSet<publisher> publishers { get; set; }
    }
}
