//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeusPark.Data.MySql
{
    using System;
    using System.Collections.Generic;
    
    public partial class discount
    {
        public int DiscountID { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string CodeID { get; set; }
        public string Title { get; set; }
        public int CodeType { get; set; }
        public string Brand { get; set; }
        public string Notice { get; set; }
        public int Quantity { get; set; }
        public int TotalQuantity { get; set; }
        public Nullable<decimal> DiscountNum { get; set; }
        public decimal ConditionNum { get; set; }
        public Nullable<double> Percentage { get; set; }
        public int Status { get; set; }
        public Nullable<bool> CanShare { get; set; }
    }
}
