//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeusPark.Data.MySql
{
    using System;
    using System.Collections.Generic;
    
    public partial class location
    {
        public location()
        {
            this.productextentionattributes = new HashSet<productextentionattribute>();
        }
    
        public int LocationID { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Province { get; set; }
    
        public virtual ICollection<productextentionattribute> productextentionattributes { get; set; }
    }
}
