//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeusPark.Data.MySql
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int OrderId { get; set; }
        public string OrderUnique { get; set; }
        public int OrderUserId { get; set; }
        public decimal OrderAmount { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public string OrderImg { get; set; }
        public string ProdIds { get; set; }
        public string OrderDetail { get; set; }
        public int Status { get; set; }
        public string Contactor { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string City { get; set; }
        public string PostCode { get; set; }
        public string Address { get; set; }
        public string Note { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public string DiscountCode { get; set; }
    }
}
