//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeusPark.Data.MySql
{
    using System;
    using System.Collections.Generic;
    
    public partial class productsaleinfo
    {
        public int SaleInfoID { get; set; }
        public int ProductID { get; set; }
        public string ProductUnique { get; set; }
        public int TotalSale { get; set; }
        public int OnSaleDay { get; set; }
        public string PayImageUrl { get; set; }
    
        public virtual product product { get; set; }
    }
}
