//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeusPark.Data.MySql
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.productimages = new HashSet<productimage>();
            this.productgroups = new HashSet<productgroup>();
            this.productproperties = new HashSet<productproperty>();
            this.productcategories = new HashSet<productcategory>();
            this.productsaleinfoes = new HashSet<productsaleinfo>();
            this.skuinfoes = new HashSet<skuinfo>();
        }
    
        public int ProductID { get; set; }
        public string ProductUnique { get; set; }
        public string Name { get; set; }
        public string DetailHtml { get; set; }
        public string MainImageUrl { get; set; }
        public Nullable<int> BuyLimit { get; set; }
        public Nullable<int> DeliveryInfoID { get; set; }
        public Nullable<int> ExtentionAttributeID { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public bool Deleted { get; set; }
    
        public virtual ICollection<productimage> productimages { get; set; }
        public virtual ICollection<productgroup> productgroups { get; set; }
        public virtual deliveryinfo deliveryinfo { get; set; }
        public virtual productextentionattribute productextentionattribute { get; set; }
        public virtual ICollection<productproperty> productproperties { get; set; }
        public virtual ICollection<productcategory> productcategories { get; set; }
        public virtual ICollection<productsaleinfo> productsaleinfoes { get; set; }
        public virtual ICollection<skuinfo> skuinfoes { get; set; }
    }
}
