//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeusPark.Data.MySql
{
    using System;
    using System.Collections.Generic;
    
    public partial class publisher
    {
        public int PublisherID { get; set; }
        public int UserID { get; set; }
        public int IdentityType { get; set; }
        public byte[] IdentityFrontImage { get; set; }
        public byte[] IdentityDueDate { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public string DetailAddress { get; set; }
        public string PostCode { get; set; }
        public string BankName { get; set; }
        public string BankAccount { get; set; }
    }
}
