//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeusPark.Data.MySql
{
    using System;
    using System.Collections.Generic;
    
    public partial class question
    {
        public long QuestionId { get; set; }
        public int ProductID { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public System.DateTime SubmitTime { get; set; }
        public string SubmitBy { get; set; }
        public Nullable<System.DateTime> AnswerTime { get; set; }
    }
}
