//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeusPark.Data.MySql
{
    using System;
    using System.Collections.Generic;
    
    public partial class skuinfo
    {
        public int InfoID { get; set; }
        public int ProductID { get; set; }
        public string SkuID { get; set; }
        public string IconUrl { get; set; }
        public double OrgPrice { get; set; }
        public double Price { get; set; }
        public string ProductCode { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual product product { get; set; }
    }
}
