//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeusPark.Data.MySql
{
    using System;
    using System.Collections.Generic;
    
    public partial class uploadhistory
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string CategoryID { get; set; }
        public string MainImg { get; set; }
        public string ProdImg { get; set; }
        public Nullable<double> Price { get; set; }
        public int UploadUser { get; set; }
        public System.DateTime UploadTime { get; set; }
        public string ProductUnique { get; set; }
        public Nullable<int> GroupID { get; set; }
    }
}
