//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeusPark.Data.MySql
{
    using System;
    using System.Collections.Generic;
    
    public partial class useraccount
    {
        public int UserID { get; set; }
        public string AccountName { get; set; }
        public string UserName { get; set; }
        public string Mail { get; set; }
        public string Telephone { get; set; }
        public string Password { get; set; }
        public System.DateTime RegisterTime { get; set; }
        public int AccountType { get; set; }
        public string OpenID { get; set; }
        public string HeadImgUrl { get; set; }
        public string UnionId { get; set; }
    }
}
